
(()=>{
  const get=id=>document.getElementById(id),list=get('applicationList'),loadBtn=get('applicationLoad'),progress=get('applicationLoadProgress'),progressCount=get('applicationLoadProgressCount'),progressTrack=get('applicationLoadProgressTrack'),progressBar=get('applicationLoadProgressBar'),statusBox=get('applicationAdminStatus'),pagination=get('applicationPagination'),pageInfo=get('applicationPageInfo');
  let page=1,totalPages=1,loaded=false;
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
  const label=value=>({new:'New',under_review:'Under Review',approved:'Approved',declined:'Declined'}[value]||value||'New');
  const adminKey=()=>get('adminKey')?.value||sessionStorage.getItem('wootenAdminKey')||'';
  function setStatus(message,ok=true){statusBox.textContent=message||'';statusBox.className='status'+(message?' show '+(ok?'ok':'bad'):'');}
  function info(name,value,full=false){return '<div class="application-info'+(full?' full':'')+'"><span>'+esc(name)+'</span><strong>'+esc(value||'—')+'</strong></div>';}
  function render(rows){
    if(!rows.length){list.innerHTML='<div class="application-empty">No account applications match the selected filters.</div>';return;}
    list.innerHTML=rows.map(row=>{const display=row.application_type==='business'?(row.business_name||row.full_name):row.full_name;return '<article class="application-card" data-application-id="'+Number(row.id)+'">'+
      '<button class="application-summary" type="button" data-application-toggle aria-expanded="false"><div><strong>'+esc(display)+'</strong><small>'+esc(row.application_number)+' • '+esc(row.full_name)+'</small></div><div><span class="application-type">'+esc(row.application_type)+'</span></div><div><span class="application-status-badge '+esc(row.status)+'">'+esc(label(row.status))+'</span><small>'+(row.reviewed_by?'Reviewed by '+esc(row.reviewed_by)+(row.reviewed_at?' • '+esc(new Date(String(row.reviewed_at).replace(' ','T')+'Z').toLocaleString()):''):'Submitted • '+esc(new Date(String(row.created_at||'').replace(' ','T')+'Z').toLocaleString()))+'</small></div><span aria-hidden="true">⌄</span></button>'+
      '<div class="application-detail" hidden><div class="application-info-grid">'+
      info('Application #',row.application_number)+info('Account Type',row.application_type)+info('Submitted',new Date(String(row.created_at||'').replace(' ','T')+'Z').toLocaleString())+
      (row.application_type==='business'?info('Legal Business Name',row.business_name)+info('DBA / Trade Name',row.dba_name)+info('Tax ID Last 4',row.tax_id_last4)+info('Years in Business',row.years_in_business):'')+
      info('Applicant / Contact',row.full_name)+info('Job Title',row.job_title)+info('Preferred Contact',row.preferred_contact)+info('Email',row.email)+info('Phone',row.phone)+info('Last Reviewed By',row.reviewed_by?row.reviewed_by+(row.reviewed_at?' • '+new Date(String(row.reviewed_at).replace(' ','T')+'Z').toLocaleString():''):'Not reviewed yet')+info('Support Notification Email',Number(row.support_email_sent)?'Sent':'Failed')+info('Applicant Confirmation Email',Number(row.applicant_email_sent)?'Sent':'Failed')+info('Applicant Confirmation SMS',Number(row.confirmation_sms_sent)?'Sent':'Failed')+info('Address',[row.address_1,row.city,row.state,row.zip_code].filter(Boolean).join(', '),true)+info('Fuel Needs / Applicant Notes',row.applicant_notes,true)+(row.notification_error?info('Notification Delivery Details',row.notification_error,true):'')+'</div>'+
      '<div class="application-documents">'+(row.has_tax_document?'<button class="secondary" type="button" data-application-file="tax">Open Tax ID Document</button>':'')+'<button class="secondary" type="button" data-application-file="identity">Open Driver’s License / State ID</button></div>'+
      '<div class="application-review"><label class="application-review-notes">Private Admin Notes<textarea data-application-notes maxlength="3000" placeholder="Add private review notes…">'+esc(row.admin_notes||'')+'</textarea></label><label class="application-review-status">Review Status<select data-application-status><option value="new"'+(row.status==='new'?' selected':'')+'>New</option><option value="under_review"'+(row.status==='under_review'?' selected':'')+'>Under Review</option><option value="approved"'+(row.status==='approved'?' selected':'')+'>Approved</option><option value="declined"'+(row.status==='declined'?' selected':'')+'>Declined</option></select><small class="application-review-meta">'+(row.reviewed_by?'Last saved by '+esc(row.reviewed_by)+(row.reviewed_at?' • '+esc(new Date(String(row.reviewed_at).replace(' ','T')+'Z').toLocaleString()):''):'Not reviewed yet')+'</small></label><button class="primary application-review-save" type="button" data-application-save>Save Review</button></div><div class="application-delete-row"><small>Permanently removes this application and all uploaded documents. Main Admin only.</small><button class="danger-db-btn application-delete-btn" type="button" data-application-delete data-application-number="'+esc(row.application_number)+'" data-application-name="'+esc(display)+'">Delete Application</button></div></div></article>';}).join('');
  }
  async function load(){let value=6;const started=Date.now();progress.hidden=false;progressBar.style.width=value+'%';progressTrack.setAttribute('aria-valuenow',String(value));progressCount.textContent='Preparing';loadBtn.disabled=true;setStatus('');const progressTimer=setInterval(()=>{value=Math.min(90,value+(value<55?9:value<78?4:2));progressBar.style.width=value+'%';progressTrack.setAttribute('aria-valuenow',String(value));progressCount.textContent='Loading… '+value+'%';},140);try{const params=new URLSearchParams({page:String(page),search:get('applicationSearch').value,status:get('applicationStatusFilter').value,type:get('applicationTypeFilter').value});const response=await fetch('/api/admin/account-applications?'+params,{headers:{'X-Admin-Key':adminKey()}});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.error||'Applications could not be loaded.');render(data.applications||[]);totalPages=Number(data.total_pages||1);page=Number(data.page||1);pageInfo.textContent='Page '+page+' of '+totalPages+' • '+Number(data.total||0)+' applications';pagination.hidden=Number(data.total||0)===0;get('applicationPrev').disabled=page<=1;get('applicationNext').disabled=page>=totalPages;setStatus(Number(data.total||0)+' account application(s) found.',true);loaded=true;}catch(error){setStatus(error.message||'Applications could not be loaded.',false);}finally{clearInterval(progressTimer);progressBar.style.width='100%';progressTrack.setAttribute('aria-valuenow','100');progressCount.textContent='100%';await new Promise(resolve=>setTimeout(resolve,Math.max(350,800-(Date.now()-started))));progress.hidden=true;progressBar.style.width='0%';progressTrack.setAttribute('aria-valuenow','0');progressCount.textContent='Preparing';loadBtn.disabled=false;}}
  async function openFile(card,kind,button){button.disabled=true;const original=button.textContent;button.textContent='Opening…';try{const id=card.dataset.applicationId;const response=await fetch('/api/admin/account-applications/'+encodeURIComponent(id)+'/'+kind,{headers:{'X-Admin-Key':adminKey()}});if(!response.ok)throw new Error(await response.text()||'Document could not be opened.');const url=URL.createObjectURL(await response.blob());const anchor=document.createElement('a');anchor.href=url;anchor.target='_blank';anchor.rel='noopener';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(error){setStatus(error.message||'Document could not be opened.',false);}finally{button.disabled=false;button.textContent=original;}}
  async function save(card,button){button.disabled=true;button.textContent='Saving…';try{const response=await fetch('/api/admin/account-applications',{method:'POST',headers:{'X-Admin-Key':adminKey(),'Content-Type':'application/json'},body:JSON.stringify({id:Number(card.dataset.applicationId),status:card.querySelector('[data-application-status]').value,admin_notes:card.querySelector('[data-application-notes]').value})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.error||'Review could not be saved.');setStatus('Application review saved.',true);await load();}catch(error){setStatus(error.message||'Review could not be saved.',false);button.disabled=false;button.textContent='Save Review';}}
  async function deleteApplication(card,button){if(!window.wootenAdminUser?.owner){setStatus('Only the Main Admin can permanently delete account applications.',false);requestAnimationFrame(()=>statusBox.scrollIntoView({behavior:'smooth',block:'center'}));return;}const number=button.dataset.applicationNumber||'',name=button.dataset.applicationName||'this applicant';const confirmed=window.confirm('Permanently delete application '+number+' for '+name+'?\n\nThis will permanently delete the complete application record, private admin notes, Tax ID document, and Driver’s License / State ID file from the server. This action cannot be undone.');if(!confirmed)return;button.disabled=true;button.textContent='Deleting…';try{const response=await fetch('/api/admin/account-applications/'+encodeURIComponent(card.dataset.applicationId),{method:'DELETE',headers:{'X-Admin-Key':adminKey(),'Accept':'application/json'}});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.error||'Application could not be deleted.');setStatus('Application '+(data.application_number||number)+' and '+Number(data.files_deleted||0)+' uploaded file(s) were permanently deleted.',true);await load();}catch(error){setStatus(error.message||'Application could not be deleted.',false);button.disabled=false;button.textContent='Delete Application';}}
  list.addEventListener('click',event=>{const card=event.target.closest('[data-application-id]');if(!card)return;const toggle=event.target.closest('[data-application-toggle]');if(toggle){const detail=card.querySelector('.application-detail'),open=detail.hidden;detail.hidden=!open;toggle.setAttribute('aria-expanded',String(open));return;}const file=event.target.closest('[data-application-file]');if(file){openFile(card,file.dataset.applicationFile,file);return;}const saveBtn=event.target.closest('[data-application-save]');if(saveBtn){save(card,saveBtn);return;}const deleteBtn=event.target.closest('[data-application-delete]');if(deleteBtn)deleteApplication(card,deleteBtn);});
  loadBtn.addEventListener('click',()=>{page=1;load();});get('applicationPrev').addEventListener('click',()=>{if(page>1){page--;load();}});get('applicationNext').addEventListener('click',()=>{if(page<totalPages){page++;load();}});get('applicationTypeFilter').addEventListener('change',()=>{page=1;load();});get('applicationStatusFilter').addEventListener('change',()=>{page=1;load();});
  let timer;get('applicationSearch').addEventListener('input',()=>{if(!loaded)return;clearTimeout(timer);timer=setTimeout(()=>{page=1;load();},350);});get('admin-tab-btn-applications').addEventListener('click',()=>{if(!loaded)load();});
})();
